💡[Feat]: Suha 파스타 타이머 구현
Swift-Coding-Club/ToolCook pull request #4
Opened 2023-02-27 11:06 UTC by sueunal

아직 부족한게 너무 많네요 일단 돌아가게만 만들었습니다!

2023-02-27 13:09 UTC, JJinuk commented
고생하셨습니다 :)

2023-02-28 07:48 UTC, kangddong requested changes
고생하셨습니다 !!! 네이밍 컨벤션이랑 공통 탭바 부분을 수정 요청드려요 !

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/ContentView.swift
> -        TabView {
저희 탭바를 활용해서 탭 별로 개인 화면을 보여줘야하는게 컨셉이라서요 ! 
탭바 살려주셔야 머지 가능할거같아요 !!

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/ContentView.swift
> -        TabView {
JoelTabView.swift도 같이 살려주셔야할거같아요 🥲

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/selectPastar.swift
> +        var pastarName : String {
case 와 name의 반환 값이 같다면 
```swift
enum PastarSelector: String {} // enum에 String을 상속 받고 rawValue를 사용하는 코드는 어떨까요 ?
```

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/selectPastar.swift
> +struct selectPastar: View {
네이밍 컨벤션에 따르면 struct니까 selectPastar 대신 SelectPasta 로 하면 좋을거같아요 !

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/selectPastar.swift
> +    enum pastarSelector {
네이밍 컨벤션에 따르면 enum니까 pastaSelector 대신 PastaSelector 로 하면 좋을거같아요 !

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/selectPastar.swift
> +struct selectPastar_Previews: PreviewProvider {
여기도 맨 앞 글자 대문자로 바꿔주세요 ~!

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/start_stop.swift
> +struct start_stop: View {
여기도 맨 앞 글자 대문자로 바꿔주세요 ~!
Swift 는 카멜 케이스를 따라주니까 start_stop 에 언더스코어도 빠져야할거같아요 !

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/start_stop.swift
> +struct start_stop_Previews: PreviewProvider {
여기도 카멜케이스에 맞춰서 작성해주세요  ~!

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/timerView.swift
> +struct timerView: View {
여기도 카멜케이스에 맞춰서 작성해주세요  ~!

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/timerView.swift
> +    enum pastarSelector {
selectPasta.swift 와 같은 것 같은데 전역으로 관리 안하신 이유가 있으실까요 ??

2023-02-28 07:48 UTC, kangddong commented on PastaTimer/PastaTimer/timerView.swift
> +struct timerView_Previews: PreviewProvider {
카멜케이스로 변경해주세요 ~

2023-02-28 09:19 UTC, sueunal commented on PastaTimer/PastaTimer/ContentView.swift
> -        TabView {
추가했습니다!

2023-02-28 09:57 UTC, kangddong commented on PastaTimer/PastaTimer/ContentView.swift
> -        TabView {
@sueunal  추가하셨으면 resolve 부탁드려요!

2023-03-02 01:03 UTC, merged